---
###############################################################################
# Cron Handlers
###############################################################################

- name: 'Handlers | restart cron'
  ansible.builtin.service:
    name: 'cron'
    state: 'restarted'
